//エラーをthrowする方法
const num = process.argv[2]
console.log(process.argv)